CREATE TABLE IF NOT EXISTS "categories" (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "users"(
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "posts"(
    "id" SERIAL PRIMARY KEY,
    "content" VARCHAR(255) NOT NULL,
    "images" VARCHAR(50)[] NOT NULL DEFAULT '{}'::VARCHAR(50)[]
);

CREATE TABLE IF NOT EXISTS "topics"(
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(50) NOT NULL,
    "meta" JSONB NOT NULL DEFAULT '{}'
);

CREATE UNLOGGED TABLE IF NOT EXISTS "sessions"(
    "id" SERIAL PRIMARY KEY,
    "token" CHAR(20) NOT NULL,
    "data" HSTORE NOT NULL
);